#pragma once

// 4J-PB - if you change this, you need to update SoundEngine::wchSoundNames[]
enum eSOUND_TYPE {
    eSoundType_MOB_CHICKEN_AMBIENT,
    eSoundType_MOB_CHICKEN_HURT,
    eSoundType_MOB_CHICKENPLOP,
    eSoundType_MOB_COW_AMBIENT,
    eSoundType_MOB_COW_HURT,
    eSoundType_MOB_PIG_AMBIENT,
    eSoundType_MOB_PIG_DEATH,
    eSoundType_MOB_SHEEP_AMBIENT,
    eSoundType_MOB_WOLF_GROWL,
    eSoundType_MOB_WOLF_WHINE,
    eSoundType_MOB_WOLF_PANTING,
    eSoundType_MOB_WOLF_BARK,
    eSoundType_MOB_WOLF_HURT,
    eSoundType_MOB_WOLF_DEATH,
    eSoundType_MOB_WOLF_SHAKE,
    eSoundType_MOB_BLAZE_BREATHE,
    eSoundType_MOB_BLAZE_HURT,
    eSoundType_MOB_BLAZE_DEATH,
    eSoundType_MOB_GHAST_MOAN,
    eSoundType_MOB_GHAST_SCREAM,
    eSoundType_MOB_GHAST_DEATH,
    eSoundType_MOB_GHAST_FIREBALL,
    eSoundType_MOB_GHAST_CHARGE,
    eSoundType_MOB_ENDERMEN_IDLE,
    eSoundType_MOB_ENDERMEN_HIT,
    eSoundType_MOB_ENDERMEN_DEATH,
    eSoundType_MOB_ENDERMEN_PORTAL,
    eSoundType_MOB_ZOMBIEPIG_AMBIENT,
    eSoundType_MOB_ZOMBIEPIG_HURT,
    eSoundType_MOB_ZOMBIEPIG_DEATH,
    eSoundType_MOB_ZOMBIEPIG_ZPIGANGRY,
    eSoundType_MOB_SILVERFISH_AMBIENT,
    eSoundType_MOB_SILVERFISH_HURT,
    eSoundType_MOB_SILVERFISH_DEATH,
    eSoundType_MOB_SILVERFISH_STEP,
    eSoundType_MOB_SKELETON_AMBIENT,
    eSoundType_MOB_SKELETON_HURT,
    eSoundType_MOB_SPIDER_AMBIENT,
    eSoundType_MOB_SPIDER_DEATH,
    eSoundType_MOB_SLIME,
    eSoundType_MOB_SLIME_ATTACK,
    eSoundType_MOB_CREEPER_HURT,
    eSoundType_MOB_CREEPER_DEATH,
    eSoundType_MOB_ZOMBIE_AMBIENT,
    eSoundType_MOB_ZOMBIE_HURT,
    eSoundType_MOB_ZOMBIE_DEATH,
    eSoundType_MOB_ZOMBIE_WOOD,
    eSoundType_MOB_ZOMBIE_WOOD_BREAK,
    eSoundType_MOB_ZOMBIE_METAL,
    eSoundType_MOB_MAGMACUBE_BIG,
    eSoundType_MOB_MAGMACUBE_SMALL,
    eSoundType_MOB_CAT_PURR,
    eSoundType_MOB_CAT_PURREOW,
    eSoundType_MOB_CAT_MEOW,
    eSoundType_MOB_CAT_HIT,
    //	eSoundType_MOB_IRONGOLEM_THROW,
    //	eSoundType_MOB_IRONGOLEM_HIT,
    //	eSoundType_MOB_IRONGOLEM_DEATH,
    //	eSoundType_MOB_IRONGOLEM_WALK,
    eSoundType_RANDOM_BOW,
    eSoundType_RANDOM_BOW_HIT,
    eSoundType_RANDOM_EXPLODE,
    eSoundType_RANDOM_FIZZ,
    eSoundType_RANDOM_POP,
    eSoundType_RANDOM_FUSE,
    eSoundType_RANDOM_DRINK,
    eSoundType_RANDOM_EAT,
    eSoundType_RANDOM_BURP,
    eSoundType_RANDOM_SPLASH,
    eSoundType_RANDOM_CLICK,
    eSoundType_RANDOM_GLASS,
    eSoundType_RANDOM_ORB,
    eSoundType_RANDOM_BREAK,
    eSoundType_RANDOM_CHEST_OPEN,
    eSoundType_RANDOM_CHEST_CLOSE,
    eSoundType_RANDOM_DOOR_OPEN,
    eSoundType_RANDOM_DOOR_CLOSE,
    eSoundType_AMBIENT_WEATHER_RAIN,
    eSoundType_AMBIENT_WEATHER_THUNDER,
    eSoundType_AMBIENT_CAVE_CAVE,
    eSoundType_PORTAL_PORTAL,
    // 4J-PB - adding some that were still text in the code
    eSoundType_PORTAL_TRIGGER,
    eSoundType_PORTAL_TRAVEL,

    eSoundType_FIRE_IGNITE,
    eSoundType_FIRE_FIRE,
    eSoundType_DAMAGE_HURT,
    eSoundType_DAMAGE_FALL_SMALL,
    eSoundType_DAMAGE_FALL_BIG,
    eSoundType_NOTE_HARP,
    eSoundType_NOTE_BD,
    eSoundType_NOTE_SNARE,
    eSoundType_NOTE_HAT,
    eSoundType_NOTE_BASSATTACK,
    eSoundType_TILE_PISTON_IN,
    eSoundType_TILE_PISTON_OUT,
    eSoundType_LIQUID_WATER,
    eSoundType_LIQUID_LAVA_POP,
    eSoundType_LIQUID_LAVA,
    eSoundType_STEP_STONE,
    eSoundType_STEP_WOOD,
    eSoundType_STEP_GRAVEL,
    eSoundType_STEP_GRASS,
    eSoundType_STEP_METAL,
    eSoundType_STEP_CLOTH,
    eSoundType_STEP_SAND,
    // soundbank 2
    eSoundType_MOB_ENDERDRAGON_END,
    eSoundType_MOB_ENDERDRAGON_GROWL,
    eSoundType_MOB_ENDERDRAGON_HIT,
    eSoundType_MOB_ENDERDRAGON_MOVE,
    eSoundType_MOB_IRONGOLEM_THROW,
    eSoundType_MOB_IRONGOLEM_HIT,
    eSoundType_MOB_IRONGOLEM_DEATH,
    eSoundType_MOB_IRONGOLEM_WALK,

    // TU14
    eSoundType_DAMAGE_THORNS,
    eSoundType_RANDOM_ANVIL_BREAK,
    eSoundType_RANDOM_ANVIL_LAND,
    eSoundType_RANDOM_ANVIL_USE,
    eSoundType_MOB_VILLAGER_HAGGLE,
    eSoundType_MOB_VILLAGER_IDLE,
    eSoundType_MOB_VILLAGER_HIT,
    eSoundType_MOB_VILLAGER_DEATH,
    eSoundType_MOB_VILLAGER_YES,
    eSoundType_MOB_VILLAGER_NO,
    eSoundType_MOB_ZOMBIE_INFECT,
    eSoundType_MOB_ZOMBIE_UNFECT,
    eSoundType_MOB_ZOMBIE_REMEDY,
    eSoundType_STEP_SNOW,
    eSoundType_STEP_LADDER,
    eSoundType_DIG_CLOTH,
    eSoundType_DIG_GRASS,
    eSoundType_DIG_GRAVEL,
    eSoundType_DIG_SAND,
    eSoundType_DIG_SNOW,
    eSoundType_DIG_STONE,
    eSoundType_DIG_WOOD,

    // 1.6.4
    eSoundType_FIREWORKS_LAUNCH,
    eSoundType_FIREWORKS_BLAST,
    eSoundType_FIREWORKS_BLAST_FAR,
    eSoundType_FIREWORKS_LARGE_BLAST,
    eSoundType_FIREWORKS_LARGE_BLAST_FAR,
    eSoundType_FIREWORKS_TWINKLE,
    eSoundType_FIREWORKS_TWINKLE_FAR,

    eSoundType_MOB_BAT_IDLE,
    eSoundType_MOB_BAT_HURT,
    eSoundType_MOB_BAT_DEATH,
    eSoundType_MOB_BAT_TAKEOFF,

    eSoundType_MOB_WITHER_SPAWN,
    eSoundType_MOB_WITHER_IDLE,   //"mob.wither.idle";
    eSoundType_MOB_WITHER_HURT,   //"mob.wither.hurt";
    eSoundType_MOB_WITHER_DEATH,  //"mob.wither.death";
    eSoundType_MOB_WITHER_SHOOT,  //"mob.wither.shoot";

    eSoundType_MOB_COW_STEP,
    eSoundType_MOB_CHICKEN_STEP,
    eSoundType_MOB_PIG_STEP,
    eSoundType_MOB_ENDERMAN_STARE,
    eSoundType_MOB_ENDERMAN_SCREAM,
    eSoundType_MOB_SHEEP_SHEAR,
    eSoundType_MOB_SHEEP_STEP,
    eSoundType_MOB_SKELETON_DEATH,
    eSoundType_MOB_SKELETON_STEP,
    eSoundType_MOB_SPIDER_STEP,
    eSoundType_MOB_WOLF_STEP,
    eSoundType_MOB_ZOMBIE_STEP,
    eSoundType_LIQUID_SWIM,
    eSoundType_MOB_HORSE_LAND,
    eSoundType_MOB_HORSE_ARMOR,
    eSoundType_MOB_HORSE_LEATHER,
    eSoundType_MOB_HORSE_ZOMBIE_DEATH,
    eSoundType_MOB_HORSE_SKELETON_DEATH,
    eSoundType_MOB_HORSE_DONKEY_DEATH,
    eSoundType_MOB_HORSE_DEATH,
    eSoundType_MOB_HORSE_ZOMBIE_HIT,
    eSoundType_MOB_HORSE_SKELETON_HIT,
    eSoundType_MOB_HORSE_DONKEY_HIT,
    eSoundType_MOB_HORSE_HIT,
    eSoundType_MOB_HORSE_ZOMBIE_IDLE,
    eSoundType_MOB_HORSE_SKELETON_IDLE,
    eSoundType_MOB_HORSE_DONKEY_IDLE,
    eSoundType_MOB_HORSE_IDLE,
    eSoundType_MOB_HORSE_DONKEY_ANGRY,
    eSoundType_MOB_HORSE_ANGRY,
    eSoundType_MOB_HORSE_GALLOP,
    eSoundType_MOB_HORSE_BREATHE,
    eSoundType_MOB_HORSE_WOOD,
    eSoundType_MOB_HORSE_SOFT,
    eSoundType_MOB_HORSE_JUMP,
    eSoundType_MOB_WITCH_IDLE,
    eSoundType_MOB_WITCH_HURT,
    eSoundType_MOB_WITCH_DEATH,
    eSoundType_MOB_SLIME_BIG,
    eSoundType_MOB_SLIME_SMALL,
    eSoundType_EATING,
    eSoundType_RANDOM_LEVELUP,

    eSoundType_FIRE_NEWIGNITE,

    eSoundType_MAX
};

// 4J-PB - if you change this, you need to update SoundEngine::wchUISoundNames[]
enum ESoundEffect {
    eSFX_Back,
    eSFX_Craft,
    eSFX_CraftFail,
    eSFX_Focus,
    eSFX_Press,
    eSFX_Scroll,
    eSFX_MAX
};

enum eMATERIALSOUND_TYPE {
    eMaterialSoundType_STONE,
    eMaterialSoundType_WOOD,
    eMaterialSoundType_GRAVEL,
    eMaterialSoundType_GRASS,
    eMaterialSoundType_METAL,
    eMaterialSoundType_GLASS,
    eMaterialSoundType_CLOTH,
    eMaterialSoundType_SAND,
    eMaterialSoundType_SNOW,
    eMaterialSoundType_LADDER,
    eMaterialSoundType_ANVIL,
};

/*
enum eSOUND_TYPE
{
"mob.chicken",
"mob.chickenhurt",
"mob.chickenplop",

"mob.cow",
"mob.cowhurt",

"mob.pig",
"mob.pigdeath",

"mob.sheep",

"mob.wolf.growl",
"mob.wolf.whine",
"mob.wolf.panting",
"mob.wolf.bark",
"mob.wolf.hurt",
"mob.wolf.death",
"mob.wolf.shake",

"mob.blaze.breathe",
"mob.blaze.hit",
"mob.blaze.death",

"mob.ghast.moan",
"mob.ghast.scream",
"mob.ghast.death",
"mob.ghast.fireball",
        "mob.ghast.charge",

        "mob.endermen.idle",
        "mob.endermen.hit",
        "mob.endermen.death",
        "mob.endermen.portal",

        "mob.zombiepig.zpig",
        "mob.zombiepig.zpighurt",
        "mob.zombiepig.zpigdeath",
        "mob.zombiepig.zpigangry",

        "mob.silverfish.say",
        "mob.silverfish.hit",
        "mob.silverfish.kill",
        "mob.silverfish.step",

        "mob.skeleton",
        "mob.skeleton.hurt",

        "mob.spider",
        "mob.spiderdeath",

        "mob.slime",
        "mob.slimeattack",

        "mob.creeper",
        "mob.creeperdeath",

        "mob.zombie",
        "mob.zombiehurt",
        "mob.zombiedeath",
        "mob.zombie.wood",
        "mob.zombie.woodbreak",
        "mob.zombie.metal",

        "mob.magmacube.big",
        "mob.magmacube.small",

        "random.bow",
        "random.bowhit",
        "random.explode",
        "random.fizz",
        "random.pop",
        "random.fuse",
        "random.drink",
        "random.eat",
        "random.burp",
        "random.splash",
        "random.click",
        "random.glass",
        "random.orb",
        "random.break",
        "random.chestopen",
        "random.chestclosed",
        "random.door_open",
        "random.door_close",

        "ambient.weather.rain",
        "ambient.weather.thunder",

        "ambient.cave.cave",

        "portal.portal",

        "fire.ignite",
        "fire.fire",

        "damage.hurtflesh",
        "damage.fallsmall",
        "damage.fallbig",

        "note.harp",
        "note.bd",
        "note.snare",
        "note.hat",
        "note.bassattack",

        "tile.piston.in",
        "tile.piston.out",

        "liquid.water",
        "liquid.lavapop",
        "liquid.lava",

        "step.stone",
        "step.wood",
        "step.gravel",
        "step.grass",
        "step.metal",
        "step.cloth",
        "step.sand",

};*/