name: Windows

# TODO: test with only pull-request
on:
  push:
    paths: &workflow_paths
      - "**.cppm"
      - "**.ixx"
      - "**.inl"
      - "**.mpp"
      - "**.ipp"
      - "**.tpp"
      - "**.txx"
      - "**.inc"
      - "**.cpp"
      - "**.hpp"
      - "**.cxx"
      - "**.hxx"
      - "**.cc"
      - "**.hh"
      - "**.c"
      - "**.h"
      - ".github/workflows/build-windows.yml"
      - ".github/workflows/actions/build-meson/action.yml"
      - "**/meson.build"
      - "flake.nix"

  pull_request:
    paths: *workflow_paths

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'dev/') }}

jobs:
  Build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build-type: ["amalgam", "full", "optimized"]
        arch: ["x86-64"]
    steps:
      - name: Cache .git folder
        uses: actions/cache@v5
        with:
          path: .git
          key: ${{ runner.os }}-git-${{ github.sha }}
          restore-keys: ${{ runner.os }}-git-

      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      # Can't use nix here, windows :(
      - name: Install tooling
        run: |
          choco install 7zip -y 
          python -m pip install meson

      - name: Restore build cache
        uses: ./.github/actions/restore-cache
        with:
          ccache_dir: ~/.cache/ccache

      - name: Compile unity
        if: ${{ matrix.build-type == 'amalgam' }}
        uses: ./.github/actions/build-meson
        with:
          dir_name: "build_${{ matrix.build-type }}"
          setup_args: "-Dunity=on -Dunity_size=99999 --vsenv -Dzlib:unity=off -Dsdl2:unity=off -Dbuildtype=release"

      - name: Compile
        if: ${{ matrix.build-type == 'full' }}
        uses: ./.github/actions/build-meson
        with:
          dir_name: "build_${{ matrix.build-type }}"
          setup_args: "-Dunity=off --vsenv"

      - name: Compile Optimized
        if: ${{ matrix.build-type == 'optimized' }}
        uses: ./.github/actions/build-meson
        with:
          dir_name: "build_${{ matrix.build-type }}"
          setup_args: "-Dunity=on -Dunity_size=99999 --vsenv -Dzlib:unity=off -Dsdl2:unity=off -Dbuildtype=release -Doptimization=3"

      - name: Package artifact
        shell: bash -e {0}
        run: |
          cp subprojects/shiggy/libs/iggy_w64.dll  build_${{matrix.build-type}}/targets/app/iggy_w64.dll
          cd build_${{matrix.build-type}}/targets/app
          7z a ../../../minecraft-client-windows-${{matrix.arch}}.zip * -x!Minecraft.Client.exe.p/

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: minecraft-client-windows-${{ matrix.build-type }}-${{ github.sha }}
          path: minecraft-client-windows-${{ matrix.arch }}.zip
          retention-days: 7

      - name: Release Nightly
        if: ${{ matrix.build-type == 'optimized' }}
        uses: softprops/action-gh-release@v3
        continue-on-error: true
        with:
          tag_name: nightly
          name: Nightly
          prerelease: true
          files: minecraft-client-windows-${{ matrix.arch }}.zip
