name: Build Windows

# TODO: test with only pull-request
on:
  push:
    paths: &workflow_paths
      - "**.cppm"
      - "**.ixx"
      - "**.inl"
      - "**.mpp"
      - "**.ipp"
      - "**.tpp"
      - "**.txx"
      - "**.inc"
      - "**.cpp"
      - "**.hpp"
      - "**.cxx"
      - "**.hxx"
      - "**.cc"
      - "**.hh"
      - "**.c"
      - "**.h"
      - ".github/workflows/build-windows.yml"
      - "**/meson.build"
      - "flake.nix"

  pull_request:
    paths: *workflow_paths

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'dev/') }}

jobs:
  Build:
    runs-on: windows-latest
    strategy:
      matrix:
        build-type: ['release','debug']
        arch: ['x86-64']
    steps:
      - name: Cache .git folder
        uses: actions/cache@v5
        with:
          path: .git
          key: ${{ runner.os }}-git-${{ github.sha }}
          restore-keys: ${{ runner.os }}-git-

      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      # Can't use nix here, windows :(
      - name: Install tooling 
        run: |
          choco install ccache -y 
          python -m pip install meson

      - name: Compile unity
        if: ${{ startsWith(matrix.build-type, 'release') }}
        uses: ./.github/actions/build-meson
        with:
          dir_name: "build_${{ matrix.build-type }}"
          setup_args: "-Dunity=on -Dunity_size=99999 --vsenv -Dzlib:unity=off -Dsdl2:unity=off"

      - name: Compile
        if: ${{ startsWith(matrix.build-type, 'debug') }}
        uses: ./.github/actions/build-meson
        with:
          dir_name: "build_${{ matrix.build-type }}"
          setup_args: "-Dunity=off --vsenv"

      - name: Package artifact
        shell: bash -e
        run: |
          cd build_${{matrix.build-type}}/targets/app
          zip -r ../../../minecraft-client-linux-${{matrix.arch}}.zip . --exclude "./Minecraft.Client.p/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: minecraft-client-windows-${{ matrix.build-type }}-${{ github.sha }}
          path: minecraft-client-windows-${{ matrix.arch }}.zip
          retention-days: 7

      - name: Release Nightly
        if: ${{ startsWith(matrix.build-type, 'release') }}
        uses: softprops/action-gh-release@v3
        with:
          tag_name: nightly
          name: Nightly
          prerelease: true
          body: ${{ github.event.workflow_run.head_commit.message }}
          files: minecraft-client-linux-${{ matrix.arch }}.zip
